

spring:
  application:
    name: ticket
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      default_schema: mydb
      use_jdbc_metadata_defaults: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


  flyway:
    locations: classpath:db/migration
    schemas: mydb
